### ISSUE TITLE
[Suggestion] Pushing player when trying to get off the border

### ISSUE THREAD

**Issue by MrBlasyMSK** [Pinesolz/WorldBorder#11]
I thought it would be great to add a push system to replace the current "freeze" so that players will not freeze when trying to enter the border.

Here below I leave you a video of how it could be:
Min 0:24
https://www.youtube.com/watch?v=RW9I0fZERMo

Referring to issue number #4, it would be good if you use some type of command like /home (in a world that before if you could go far) to try to get out of the edge, that it teleported to the world of spawn and the plugin said: You've reached the world border

**Comment by Pinesolz** [comment]
added
