### ISSUE TITLE
Item to bypass border

### ISSUE THREAD

**Issue by Tzll** [Pinesolz/WorldBorder#12]
add an admin item that allows u to bypass border

**Comment by MrBlasyMSK** [comment]
@Tzll 
https://github.com/Pinesolz/WorldBorder/issues/10

Please close the issue

**Comment by Tzll** [comment]
> @Tzll
> #10
> 
> Please close the issue

bro, who cares

**Comment by MrBlasyMSK** [comment]
It is simply absurd to add an "admin" object to get through the barrier.

For that there are the permissions or the OP, to be able to execute actions and that others cannot

> > @Tzll
> > #10
> > Please close the issue
> 
> bro, who cares

**Comment by Tzll** [comment]
> It is simply absurd to add an "admin" object to get through the barrier.
> 
> For that there are the permissions or the OP, to be able to execute actions and that others cannot
> 
> > > @Tzll
> > > #10
> > > Please close the issue
> > 
> > 
> > bro, who cares

idc

**Comment by MCPEAbdu77** [comment]
Ke hj  from him did juice ygvb yin hkn yhfd hjkc ghbb

**Comment by Tzll** [comment]
> Work on a fork instead of talking to people who don't even care about their own creation.

me?

**Comment by Endermanbugzjfc** [comment]
> > Work on a fork instead of talking to people who don't even care about their own creation.
> 
> me?

I mean, command permission is quite important. You should add permissions.

**Comment by Endermanbugzjfc** [comment]
And sorry I didn't mean to blame you. I was telling him to make a fork if the author refuses to implement what he wants.
![image](https://user-images.githubusercontent.com/53002741/131834568-e44f7d4b-2e71-4d2b-a622-4ad54d6e772f.png)

**Comment by Pinesolz** [comment]
God #10 is the exact same thing... why you ppl gotta be so sensitive
