### ISSUE TITLE
I need help to put the border

### ISSUE THREAD

**Issue by MrBlasyMSK** [Pinesolz/WorldBorder#7]
Could you help me to put my world at 10000 blocks maximum?

That is, I want to limit my world to 10000 blocks maximum, but I don't know what number I have to put in the config because it is a bit confusing.

10000-----10000
|⠀⠀⠀⠀⠀⠀⠀⠀⠀|
|⠀⠀⠀⠀⠀⠀⠀⠀⠀|
|⠀⠀⠀   0 ⠀  ⠀⠀⠀| 
|⠀⠀⠀⠀⠀⠀⠀⠀⠀| 
|⠀⠀⠀⠀⠀⠀⠀⠀⠀|
10000-----10000

Like this

**Comment by Pinesolz** [comment]
Hello There,

If you'd like your world size to be 10000 blocks, you'd need to set that it the configuration as so:
> world: 10000 # Border World and Size of Border.

From there your border should set to the proper size! The diagram is just there to help players gain a better understaning of the border -- in no way does it affect the actual configuration!

> If this issue has been resolved, feel free to close this issue.

If you need anything else, I'd be happy to assist. Sorry for the delayed response!

Thanks for your time,

> Soulz (Pinesolz)
> Head Developer and Founder of DemeterCraft
> Discord.gg/kFacgS29ay
