### ISSUE TITLE
[BUG] The default message does not appear

### ISSUE THREAD

**Issue by MrBlasyMSK** [Pinesolz/WorldBorder#8]
I have added the plugin and I have gone to the limit of the coordinates, but no message appears, only this text appears

![image](https://user-images.githubusercontent.com/85447029/131320033-a93dc863-4bc4-476b-a7c9-624de6e64bb8.png)

PHP 8.0.10
Pocketmine 3.22.2
Device: Windows10

**Comment by Pinesolz** [comment]
Hello there, 

Thank you for awaring me of this issue. 

However, that is odd?! It works just fine for me! Please ensure that you have set the message via config. The default display message should be:
> Error: You've reached the world border!

I'll have to test this myself... 

Thanks for your time,

>Soulz (Pinesolz)
Head Developer and Founder of DemeterCraft
Discord.gg/kFacgS29ay
